
services:
  web:
    build: .
    command: python -u wsgi.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - appnet

  mongo:
    image: mongo:latest
    hostname: rouge-data
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mongo-data:
