services:    # Define services
  app:       # Service name
    build: .
    command: python -u wsgi.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    
  db:
    image: mongo:latest
    container_name: mongodb
    hostname: localhost
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=arinzingade
      - MONGO_INITDB_ROOT_PASSWORD=Napobose@01
    ports:
      - 27017:27017
