
services:
  web:
    build: .
    command: python -u wsgi.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/test_data
    depends_on:
      - mongo
    networks:
      - appnet

  mongo:
    image: mongo:latest
    hostname: test_mongodb
    ports:
      - "27017:27017"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
